# -*- coding: utf-8 -*-
"""Algoritmo-Backtracking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vTa8Uh5H271ylr3Z85knHP_qPpb2XVrj
"""

def Backtracking(G, s, d):
  n = len(G)
  l = [s]
  visited = [False]*n

  for i in range(n):
    if s == d:
      return l
    else:
      if not visited[s]:
        visited[s] = True
        for v in G[s]:
          l.append(v)
          s = v
          Backtracking(G, s, d)

  return l