# -*- coding: utf-8 -*-
"""Algoritmo_BruteForce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rt0M3dMcL--_cpLL7naAO-_AxFwKnoMC
"""

def BruteForce(G,s):
  n=len(G)
  visited=[False]*n
  m = a[s]

  for i in range (len(a)):
    if a[i] > m:
      m = a[i]
  return m
    else:
      if not visited[s]:
        visited[s] = True
        for v in G[s]:
          m.append(v)
          s = v
          BruteForce(G,s)

  return m