# -*- coding: utf-8 -*-
"""Algoritmo-Backtracking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vTa8Uh5H271ylr3Z85knHP_qPpb2XVrj
"""

def Backtracking(G, s):
  n = len(G)
  visited = [False]*n
  f = [None]*n

  def Backtracking1(e):
    visited[e] = True
    for v in G[e]:
      if not visited[v]:
        f[v] = e
        Backtracking1(v)

  Backtracking1(s)

  return f